ALTER TABLE "User" ADD COLUMN "idleHeroHair" TEXT NOT NULL DEFAULT 'short';
ALTER TABLE "User" ADD COLUMN "idleHeroOutfit" TEXT NOT NULL DEFAULT 'dojo';
ALTER TABLE "User" ADD COLUMN "idleHeroColor" TEXT NOT NULL DEFAULT 'red';
